# Generated by Django 2.2.4 on 2019-08-14 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='ProfilePicture')),
                ('contact_info', models.CharField(max_length=50)),
                ('current_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='driver.Location')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_pickup', to='driver.Location')),
            ],
        ),
    ]
